name: deploy-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    name: Deploy to Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Allow one concurrent deployment
    concurrency:
      group: pages
      cancel-in-progress: true

    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: export WORK_DIR
        run: echo "WORK_DIR=${RUNNER_TEMP}/doc" >> $GITHUB_ENV

      - name: Copy examples/* to work dir
        run: |
          mkdir -p ${WORK_DIR}
          cp examples/* ${WORK_DIR}

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .tool-versions

      - name: Replace "../dist/rb-wasm-vdom.rb" to jsdelivr url in *.html
        run: |
          version=$(node -p "require('./package.json').version")
          find ${WORK_DIR} -type f -name "*.html" -print0 | xargs -0 sed -i "s|../dist/rb-wasm-vdom.rb|https://cdn.jsdelivr.net/npm/@sue445/rb-wasm-vdom@${version}/dist/rb-wasm-vdom.rb|g"

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ${{ env.WORK_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

      - name: Slack Notification (not success)
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.slack-webhook }}
